factcheck_api_key = ""  
out_dir = "data"
max_workers = 31
factcheck_sleep = 1.0
max_inflight = 200
min_tokens = 5
max_query_size = 512
language_code = "pt-BR"
show_progress_bar = true

[deduplication]
threshold = 0.7
ngram = 5
seed = 3
num_perm = 128
bands = 50

